  ---
 - hosts: all
   become: yes
   connection: ssh
   tasks:
    - name: Create new group
      group: name=developer state=present
    - name: Create a login user
      user:
       name: docker_user
       password: A_delta@1v2345
       groups: developer
       append: yes
       state: present
       shell: /bin/bash      
       system: no            
       createhome: yes       
       home: /home/developer
       generate_ssh_key: yes
       ssh_key_bits: 4096
       ssh_key_file: .ssh/id_rsa
    - name: Install docker
      pip: name=docker-py state=present
      notify : Start docker service
    - name: Install Maven
      apt: pkg=maven state=latest update_cache=yes
    - name: Start docker service
      service: name=docker state=started 
